export const SPOKEN_LANGUAGES = [
  "English",
  "Spanish",
  "French",
  "German",
  "Mandarin",
  "Hindi",
  "Arabic",
  "Portuguese",
  "Bengali",
  "Russian",
  "Japanese",
  "Punjabi",
  "Marathi",
  "Telugu",
  "Turkish",
  "Korean",
  "Vietnamese",
  "Tamil",
  "Urdu",
  "Italian",
  "Other",
] as const;

export const LANGUAGES = SPOKEN_LANGUAGES; // Alias for backward compatibility if needed, using Spoken as primary "Language" preference

export const ROLES = [
  "Frontend Developer",
  "Backend Developer",
  "Fullstack Developer",
  "Mobile Developer",
  "DevOps Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Engineer",
  "Cloud Architect",
  "Cybersecurity Engineer",
  "Game Developer",
  "Embedded Systems Engineer",
  "QA Engineer",
  "SRE (Site Reliability Engineer)",
  "Data Engineer",
  "Blockchain Developer",
  "Product Manager",
  "UI/UX Designer",
  "VFX Artist",
  "Graphics Programmer",
  "Network Engineer",
  "Student",
  "Other",
] as const;

export const DOMAINS = [
  "Fintech",
  "Edtech",
  "E-commerce",
  "Healthcare",
  "Social Media",
  "Gaming",
  "Blockchain/Web3",
  "AI/ML",
  "Cybersecurity",
  "Cloud Computing",
  "IoT",
  "Enterprise",
  "Adtech",
  "Medtech",
  "Proptech",
  "Logistics",
  "Automotive",
  "Aerospace",
  "Robotics",
  "Entertainment",
  "Travel/Hospitality",
  "Other",
] as const;

export const TECH_STACK = [
  // Frontend
  "React",
  "Next.js",
  "Vue.js",
  "Nuxt.js",
  "Angular",
  "Svelte",
  "Solid.js",
  "Remix",
  "Astro",
  "TailwindCSS",
  "Bootstrap",
  "Material UI",
  
  // Backend
  "Node.js",
  "Express",
  "NestJS",
  "Fastify",
  "Django",
  "Flask",
  "FastAPI",
  "Spring Boot",
  "ASP.NET Core",
  "Ruby on Rails",
  "Laravel",
  "Symfony",
  "Phoenix",
  
  // Mobile
  "React Native",
  "Flutter",
  "SwiftUI",
  "Jetpack Compose",
  "Ionic",
  
  // Database & Tools
  "Docker",
  "Kubernetes",
  "AWS",
  "GCP",
  "Azure",
  "Firebase",
  "Supabase",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Redis",
  "GraphQL",
  "Terraform",
  "Ansible",
  "Jenkins",
  "Git",
  "Linux",
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "Go",
  "Rust",
  "Other",
] as const;

export const EXPERIENCE_LEVELS = ["0-1", "1-3", "3-5", "5-8", "8+"] as const;
